/*
 */

#define KEY_TOGGLE_MOUSE_MODE KEY_LEFTMETA

#define KEY_MOVE_UP KEY_I
#define KEY_MOVE_DOWN KEY_K
#define KEY_MOVE_LEFT KEY_J
#define KEY_MOVE_RIGHT KEY_L

#define KEY_MOUSE_LEFT KEY_SPACE
#define KEY_MOUSE_MIDDLE KEY_P
#define KEY_MOUSE_RIGHT KEY_O
#define KEY_MOUSE_SCROLL_FORWARD KEY_9
#define KEY_MOUSE_SCROLL_BACKWARD KEY_APOSTROPHE
